### ISSUE TITLE
How to pass this file value in file param UploadMedia action method? 

### ISSUE THREAD

**Issue by Shivam-kalra** [yuenkik6/WABA360Dialog.NET#2]
In Waba360DialogController, UploadMedia Action method how to pass file param value, Is it base64 value or image binary in string format.

{
"file": "string", - How to pass this file value?
"contentType": "string"
}

Thanks in advance.

**Comment by sleekflowalexyuen** [comment]
I mistakenly used [FromBody] for that API Endpoint, it should use [FromForm] instead.
Just pushed a fix with some for that.
Thanks!

**Comment by Shivam-kalra** [comment]
Hi @sleekflowalexyuen 

Thanks for the quick response.
I 'll check the fix and close the issue as well.

Meanwhile,  Are you working or any future plan to work on any front end platform to consume these WABA 360 Dialog API.

I do have similar interest and my working on building a tool, If you have any interest to collaborate, I 'll more than happy to  connect further.

Regards,
Shivam Kalra

**Comment by Shivam-kalra** [comment]
Hi @sleekflowalexyuen <https://github.com/sleekflowalexyuen>

Thanks for the quick response.
I'll check the fix and close the issue as well.

Meanwhile, Are you working or any future plan to work on any front-end
platform to consume these WABA 360 Dialog APIs.

I do have a similar interest and my working on building a tool, If you have
any interest to collaborate, I'll more than happy to connect further.

Regards,
Shivam Kalra

**Comment by sleekflowalexyuen** [comment]
This plugin is actually used for my company SasS project called Sleekflow, and I contribute mainly for backend part.
