### ISSUE TITLE
BODY has unexpected field(s)

### ISSUE THREAD

**Issue by Estados** [yuenkik6/WABA360Dialog.NET#3]
Hello,

Message template 'components' param contains unexpected field(s)

component of type BODY has unexpected field(s)
code_expiration_minutes, add_security_recommendation 

When creating a Template the above fields are unexpected. 

Kind Regards,
Rainer

**Comment by yuenkik6** [comment]
Hi Rainer, thanks for the feedback!
These two field should sit inside TemplateMessageComponentObject instead, will publish a fix soon

**Comment by yuenkik6** [comment]
Published version 1.0.2, should solve the issue
